---
- hosts: load_balancers
  user: deploy
  sudo: true
  tasks:
    - name: ensure haproxy is up to date
      apt: pkg=haproxy state=latest
    - name: enable init script
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
