---
taskBackend:
  redisSettings:
    host: "127.0.0.1"
    port: 6379
  rabbitSettings:
    host: "127.0.0.1"
    port: 1234
    username: R4bbit
    password: R4bbit
  postgresSettings:
    host: "127.0.0.1"
    port: 5432
    username: tasks_api
    password: test
    database: tasks
userBackend:
  redisSettings:
    host: "127.0.0.1"
    port: 6379
  rabbitSettings:
    host: "127.0.0.1"
    port: 1234
    username: R4bbit
    password: R4bbit
  postgresSettings:
    host: "127.0.0.1"
    port: 5432
    username: accounts_api
    password: test
    database: accounts
