---
- hosts: load_balancers
  user: deploy
  sudo: true
  tasks:
    - name: ensure haproxy is up to date
      apt: pkg=haproxy state=latest
    - name: enable init script
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy
    - name: write haproxy configuration
      template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0644 owner=root group=haproxy
      notify:
        - restart haproxy
    - name: whitelist web servers redis access
      with_items: groups.web_servers
      command: ufw allow from {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} to any port 6379 proto tcp
    - name: whitelist web servers rabbit access
      with_items: groups.web_servers
      command: ufw allow from {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} to any port 5672 proto tcp
    - name: whitelist web servers postgres access
      with_items: groups.web_servers
      command: ufw allow from {{ hostvars[item]['ansible_eth0']['ipv4']['address'] }} to any port 5432 proto tcp
    # - name: whitelist workers
    #  command: ufw allow
    - name: whitelist universally allowed ports
      command: ufw allow {{ item }}
      with_items:
        - http
        - https
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
