---
- hosts: load_balancers
  user: deploy
  sudo: true
  tasks:
    - name: ensure haproxy is up to date
      apt: pkg=haproxy state=latest
    - name: enable init script
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy
    - name: write haproxy configuration
      template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0640 owner=root group=root
      notify:
        - restart haproxy
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
