---
- hosts: all
  sudo: true
  tasks:
    - name: update apt
      apt: update_cache=yes cache_valid_time=3600
    - name: install vim
      apt: pkg=vim-nox state=latest
    - name: install fail2ban
      apt: pkg=fail2ban state=latest
    - name: install add-apt-repository
      apt: pkg=python-software-properties state=latest
    - name: ensure java is installed
      apt: pkg=openjdk-7-jre-headless state=latest
    - name: ensure libgmp is installed
      apt: pkg=libgmp-dev state=latest
    - name: symlink libgmp .so file to libgmp.so
      command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so creates=/usr/lib/libgmp.so
    - name: symlink libgmp .so file to libgmp.so.3
      command: ln -s /usr/lib/x86_64-linux-gnu/libgmp.so.10 /usr/lib/libgmp.so.3 creates=/usr/lib/libgmp.so.3
    - name: create adm group
      group: name=adm
    - name: create logstash user
      user: name=logstash groups=adm
    - name: create logstash folder
      file: path=/opt/logstash state=directory group=adm owner=logstash
    # - name: create logstash configuration folder
      # file: path=/home/logstash/configurations state=directory owner=logstash
    # write upstart config
    - name: write logstash agent upstart
      template: src=templates/logstash_agent_upstart dest=/etc/init.d/logstash_agent mode=0644 owner=root
    - name: write logstash agent config
      template: src=templates/agent.conf dest=/etc/agent.conf mode=0644 owner=root
    - name: Download logstash agent
      get_url: url=https://logstash.objects.dreamhost.com/release/logstash-1.2.0-flatjar.jar dest=/home/logstash/logstash-1.2.0.jar
    # - name: disable root ssh
    #- name: install unattended-upgrades
    #- name: install logwatch
# - hosts: web_servers
- hosts: development
  sudo: true
  tasks:
    - name: ensure build-essential is installed
      apt: pkg=build-essential state=latest
    - name: add node ppa
      apt_repository: repo='deb http://ppa.launchpad.net/chris-lea/node.js/ubuntu precise main' state=present
    - name: ensure node is installed
      apt: pkg=nodejs state=latest
    # - name: ensure grunt is installed
    #   npm: name=grunt-cli global=yes state=latest
    # # - name: ensure less is installed
    # - name: ensure jade is installed
    #   npm: name=jade global=yes state=latest
    # # - name: ensure bower is installed
    # - name: ensure karma is installed
    #   npm: name=karma global=yes state=latest
- hosts: development
  tasks:
    - name: ensure dev folder exists
      file: path=dev state=directory
    - name: Comment out line which prevents loading bash profile by ssh
      lineinfile: dest=~/.bashrc regexp='[ -z "$PS1" ] && return' line='# [ -z "$PS1" ] && return' state=present
      when_string: $ansible_pkg_mgr == 'apt'
    - name: ensure shell exports are set up
      lineinfile: dest=~/.bashrc regexp='^export PATH' line='export PATH=/usr/local/share/npm/bin/:$HOME/.cabal/bin:$HOME/dev/bin:$PATH'
    - name: get ghc tarfile
      get_url: url=http://www.haskell.org/ghc/dist/7.6.3/ghc-7.6.3-x86_64-unknown-linux.tar.bz2 dest=~/ghc-7.6.3.tar.bz2
    - name: unpack ghc tarfile
      command: tar xjf ghc-7.6.3.tar.bz2 creates=~/ghc-7.6.3
    - name: install ghc
      shell: cd ~/ghc-7.6.3 && ./configure --prefix=$HOME/dev/ && make install && cd ~ creates=~/dev/bin/ghc
    - name: get cabal 1.18
      get_url: url=http://hackage.haskell.org/packages/archive/cabal-install/1.18.0/cabal-install-1.18.0.tar.gz dest=~/cabal-install-1.18.0.tar.gz
    - name: unpack cabal tarfile
      command: tar xzf cabal-install-1.18.0.tar.gz creates=~/cabal-install-1.18.0
    - name: install cabal
      shell: cd ~/cabal-install-1.18.0 && ./bootstrap.sh && cd .. creates=~/.cabal/bin/cabal
    # - name: install ghcjs
- hosts: message_brokers
  sudo: true
  tasks:
    - name: add official rabbitmq apt-repo key
      apt_key: url=http://www.rabbitmq.com/rabbitmq-signing-key-public.asc
    - name: add official rabbitmq apt-repo
      apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present
    - name: create rabbit config directory
      file: dest=/etc/rabbitmq state=directory
    - name: ensure rabbitmq group exists
      group: name=rabbitmq
    - name: write rabbit configuration
      template: src=templates/rabbitmq.config.j2 dest=/etc/rabbitmq/rabbitmq.config mode=0644 owner=root group=rabbitmq
      notify:
        - restart rabbit
    - name: ensure rabbit is up to date
      apt: pkg=rabbitmq-server state=latest
      notify:
        - restart rabbit
    - name: enable rabbitmq management interface
      template: src=templates/enabled_plugins dest=/etc/rabbitmq/enabled_plugins group=rabbitmq owner=rabbitmq
      notify: restart rabbit
  handlers:
    - name: restart rabbit
      service: name=rabbitmq-server state=restarted
- hosts: caches
  sudo: true
  tasks:
    - name: add redis ppa key
      apt_key: url="http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0xB9316A7BC7917B12"
    - name: add redis ppa
      apt_repository: repo="deb http://ppa.launchpad.net/chris-lea/redis-server/ubuntu precise main"
    - name: ensure redis is up to date
      apt: pkg=redis-server state=latest
    # - name: set listening interface
      # lineinfile: dest=/etc/redis/redis.conf regexp="^bind" line="bind {{ ansible_eth0['ipv4']['address'] }}"
    - name: set listening port
      lineinfile: dest=/etc/redis/redis.conf regexp="^port" line="port $redis_port"
      notify:
        - restart redis
  handlers:
    - name: restart redis
      service: name=redis-server state=restarted
- hosts: search_nodes:log_servers
  sudo: true
  tasks:
    - name: ensure elasticsearch user exists
      user: name=elasticsearch
    - name: download elasticsearch deb
      get_url: url=https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-0.90.3.deb dest=/home/elasticsearch/elasticsearch-0.90.3.deb
    - name: install elasticsearch
      command: dpkg -i /home/elasticsearch/elasticsearch-0.90.3.deb creates=/usr/share/elasticsearch
- hosts: log_viewers
  sudo: true
  tasks:
    - name: ensure kibana user exists
      user: name=kibana
    - name: get latest version of kibana
      get_url: force=yes url=https://github.com/elasticsearch/kibana/archive/master.tar.gz dest=/home/kibana/kibana.tar.gz
    - name: ensure nginx is installed
      apt: pkg=nginx state=latest
    - name: disable nginx default site
      file: path=/etc/nginx/sites-enabled/default state=absent
      notify:
        - restart nginx
    - name: write static fileserving configuration
      template: src=templates/kibana dest=/etc/nginx/sites-enabled/kibana mode=0644 owner=root
      notify:
        - restart nginx
    - name: deploy kibana to fileserving directory
      command: tar xzf /home/kibana/kibana.tar.gz chdir=/usr/share/nginx/www
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
- hosts: databases
  sudo: true
  tasks:
    - name: ensure postgres dev lib is installed
      apt: pkg=libpq-dev state=latest
    - name: ensure psycopg2 is installed
      apt: pkg=python-psycopg2
    - name: install postgres
      apt: pkg=postgresql
    - name: install postgres contrib
      apt: pkg=postgresql-contrib
    - name: set listening postgres port
      lineinfile: dest=/etc/postgresql/9.1/main/postgresql.conf regexp="^port" line="port = $postgres_port"
      notify:
        - restart postgres
  handlers:
    - name: restart postgres
      service: name=postgresql state=restarted
- hosts: databases
  sudo: true
  sudo_user: postgres
  tasks:
    - name: create queueing errors database
      postgresql_db: name=queueing port=5433
    - name: create accounts database
      postgresql_db: name=accounts port=5433
    - name: create tasks database
      postgresql_db: name=tasks port=5433
- hosts: load_balancers
  sudo: true
  tasks:
    - name: ensure haproxy is up to date
      apt: pkg=haproxy state=latest
    - name: enable init script
      lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
      notify:
        - restart haproxy
    - name: write haproxy configuration
      template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg mode=0644 owner=root group=haproxy
      notify:
        - restart haproxy
  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted
# - hosts: search_nodes
- hosts: all
  sudo: true
  tasks:
    # - name: create logstash agent upstart script
      # assemble: src=/home/logstash/configurations dest=/etc/agent.conf
