---
- hosts: caches
  user: deploy
  sudo: true
  tasks:
    - name: ensure redis is up to date
      apt: pkg=redis-server state=latest
    - name: set listening interface
      lineinfile: dest=/etc/redis/redis.conf regexp="^bind" line="bind = {{ ansible_eth0['ipv4']['address'] }}"
    - name: set listening port
      lineinfile: dest=/etc/redis/redis.conf regexp="^port" line="port = {{ redis_port }}"
      notify:
        - restart redis
    - name: whitelist load balancers
      
  handlers:
    - name: restart redis
      service: name=redis state=restarted
